### ISSUE TITLE
Display drivers for Pinetab broken 

### ISSUE THREAD

**Issue by LouisDK1** [sailfish-on-dontbeevil/issues-dontbeevil#14]
It seems like the display drivers for the current 3.3.0.16 build of SFOS for the early adopters Pinetab are currently broken as I fail to get anything on the screen after booting the sd card prepared by the "flash it" script.

I suspect this might have something to do with it: https://gitlab.com/postmarketOS/pmaports/-/merge_requests/1627 and an update binutils might solve this: https://gitlab.com/postmarketOS/pmaports/-/issues/819

Can someone else with an early adapters Pinetab confirm this?

**Comment by LouisDK1** [comment]
I tried using the flash-it script from the 1st of November 2020. While "Pinetab" options does not seem to boot at all the "pinetabdev" option gives light on the screen but I can't see anything nor does Sailfish boot.

**Comment by LouisDK1** [comment]
@piggz
Hope it's okay to tag you.
I this issue should be moved to the issues page under "flash-it" I'll do so.

**Comment by LouisDK1** [comment]
This seems to have been fixed by now.

**Comment by piggz** [comment]
It has!
